### ISSUE TITLE
[NumberGuesser] input.Equals("q")

### ISSUE THREAD

**Issue by pavel-b-novikov** [anastasia-kazantseva/nsudotnet#1]
Почему вы пишете вот так? Как надо писать в .NET и почему?

**Comment by pavel-b-novikov** [comment]
Оу.. да вы пишете еще более странно
```Math.Sign(guess.CompareTo(_random))```

UPD: а, не, до меня дошло. Извините, не проснулся. Этот вопрос не считается

**Comment by pavel-b-novikov** [comment]
```csharp
default:
            Console.WriteLine("WTF???");
            break;
```

И опять - даже sign-у нельзя доверять?

**Comment by anastasia-kazantseva** [comment]
input.Equals("q") - так писать нельзя, потому что может прилететь NullReferenceException
следовательно, "q".equals(input) - то, что нужно
По поводу sign - сначала там не было сайна и default в данном коде нечто вроде рудиментов (забыла убрать)

**Comment by pavel-b-novikov** [comment]
Да господи, зачем вы в C# используете Equals? В C# этого (в случае со строками) не надо делать.
Я пытаюсь от вас добиться ответа почему.

**Comment by anastasia-kazantseva** [comment]
в C# предпочтительнее использовать оператор ==, так как для строк он перегружен и сравнение осуществляется по значениям, а не по ссылкам

**Comment by pavel-b-novikov** [comment]
Ну хоть чем-то C# начал отличаться от java. Алилуйя.
