### ISSUE TITLE
[NumberGuesser] catch

### ISSUE THREAD

**Issue by pavel-b-novikov** [anastasia-kazantseva/nsudotnet#3]
Какие exception-ы могут всплыть в этом коде?

**Comment by anastasia-kazantseva** [comment]
как уже упоминалось в issue чуть ниже - NullReferenceException
и вот еще, если вам захочется играть в эту великолепную игру более 1000 раз (размер массива _history), то лучше так не делать, ибо IndexOutOfRangeException

**Comment by pavel-b-novikov** [comment]
Ну.. ну ладно, пусть будет
