### ISSUE TITLE
[Enigma] Kazantseva.Nsudotnet.Enigma.exe

### ISSUE THREAD

**Issue by pavel-b-novikov** [anastasia-kazantseva/nsudotnet#4]
А что если пользователь переименует .exe? Как вывести правильно?

**Comment by anastasia-kazantseva** [comment]
Аааааааа! Что?
Вывести правильно - вывести действительное имя исполняемого файла в консоль? Или вы имели в виду что-то другое?

**Comment by pavel-b-novikov** [comment]
да, я имел в виду вывод именно исполняемого файла в консоль, вы все правильно поняли

**Comment by anastasia-kazantseva** [comment]
как вариант, можно получать имя файла так: Environment.GetCommandLineArgs()[0]

**Comment by pavel-b-novikov** [comment]
Как вариант, но оно выдает полный путь к исполняемому файлу. А вы не того эффекта ожидали.

**Comment by anastasia-kazantseva** [comment]
эмпирическим путем проверила, что выводится не полный путь к исполняемому файлу, а то, что ожидает увидеть пользователь

**Comment by pavel-b-novikov** [comment]
Я проверил практическим, так как не использовал эту функциональность доселе. У меня вывелся полный. Так что есть вариант лучше.

**Comment by anastasia-kazantseva** [comment]
можно попробовать так: System.AppDomain.CurrentDomain.FriendlyName
запустила, проверила - все ок (но с предыдущим вариантом у меня тоже не возникло проблем при запуске на моем ноутбуке)

**Comment by pavel-b-novikov** [comment]
вот этот вариант уже лучше, на нем и остановимся.
