### ISSUE TITLE
[Enigma] Decryptor/Encryptor

### ISSUE THREAD

**Issue by pavel-b-novikov** [anastasia-kazantseva/nsudotnet#5]
Такая реализация декриптора/енкриптора требует реализации Dispose pattern-а вокруг него

**Comment by anastasia-kazantseva** [comment]
Как вам такое предложение?
BasicCrypt реализует интерфейс IDisposable и определяет два метода - 
public void Dispose()
  {
  DisposeManagedResources();
  }
 
  protected virtual void DisposeManagedResources() {}

**Comment by anastasia-kazantseva** [comment]
Ой, что-то странновато звучит
сейчас еще чуть-чуть подумаю

**Comment by pavel-b-novikov** [comment]
Не, идея тащемта нормальная. Только надо и сам алгоритм вывести в protected-поле

**Comment by anastasia-kazantseva** [comment]
этот вопрос с вами уже обсуждали
вы, вроде как, не против варианта с оберткой содержимого метода Crypt в дополнительный using (SymmetricalAlgorithm _algorithm = GetAlgorithm(algorithm))

**Comment by pavel-b-novikov** [comment]
Дык а где оно? в коде нет

**Comment by anastasia-kazantseva** [comment]
Сейчас будет

**Comment by anastasia-kazantseva** [comment]
сделан коммит с исправлениями
